services:
  server:
    image: docker.io/hugomods/hugo:exts
    command: server -D --disableFastRender --renderToMemory
    volumes:
      - ./:/src
      - ~/hugo_cache:/tmp/hugo_cache
    ports:
      - 1313:1313
